import Nav from '@/components/Nav'
import './globals.css'
import '@/app/assets/var.scss'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { getTagList } from '@/api/tag'
import React, { cloneElement } from 'react'
const inter = Inter({
	subsets: ['latin'],
})

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default async function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang="en">
			<body
				className={inter.className}
				style={{
					backgroundImage: "url('https://a1ex.vip/api/default-cover')",
					backgroundAttachment: 'fixed',
					backgroundSize: 'cover',
				}}
			>
				<div className="flex min-h-screen flex-col items-center justify-between  bg-[url('https://a1ex.vip/api/default-cover')] bg-fixed bg-cover">
					<div className="h-screen w-full">
						<Nav />
					</div>
				</div>
				{children}
			</body>
		</html>
	)
}
